### ISSUE TITLE
Commented lines of code

### ISSUE THREAD

**Issue by Mu7ammadAbed** [GSG-G10/news-website-team4#63]
Why there's a full commented section in the production version of the code?

https://github.com/GSG-G10/news-website-team4/blob/9823d45245a6e722a6c00e5a12cf6caee64d2b0c/index.html#L543-L574

and why this section exists in the production?

https://github.com/GSG-G10/news-website-team4/blob/9823d45245a6e722a6c00e5a12cf6caee64d2b0c/index.html#L192-L193

**Comment by Ahmad-Omar** [comment]
The weather section is in the production where it is processed with javascript
